CREATE TABLE "AUTHORS" (
	"ID"	INTEGER,
	"ISSUE_ID"	INTEGER,
	"NAME"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "CLASSES" (
	"ID"	INTEGER,
	"NAME"	TEXT,
	"ISSUE_ID"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "CODE" (
	"ISSUE_ID"	INTEGER,
	"CHANGES"	TEXT,
	FOREIGN KEY("ISSUE_ID") REFERENCES "ISSUE"("ISSUE_ID")
);

CREATE TABLE "CODE_DETAILS" (
	"ISSUE_ID"	INTEGER,
	"NO_OF_CLASSES"	INTEGER,
	"NO_OF_LINES"	INTEGER,
	"NO_OF_AUTHORS"	INTEGER
, "COMPLEXITY"	INTEGER);


CREATE TABLE "COMMENTS" (
	"ISSUE_ID"	INTEGER,
	"COMMENT"	TEXT,
	"PROCESSED_COMMENTS"	TEXT,
	"ID"	INTEGER,
	FOREIGN KEY("ISSUE_ID") REFERENCES "ISSUE"("ISSUE_ID"),
	PRIMARY KEY("ID")
);

CREATE TABLE "CONFIGURATION" (
	"DBLOC"	TEXT,
	"USE_SSL"	TEXT,
	"IGNORE_CERT"	TEXT,
	"ACCESS_TOKEN"	TEXT,
	"REPONAME"	TEXT,
	"RECORD_FROM"	INTEGER,
	"RECORD_TO"	INTEGER
);
CREATE TABLE "ISSUE" (
	"TITLE"	TEXT,
	"REPORTER"	TEXT,
	"OPEN_DATE"	TEXT,
	"CLOSE_DATE"	TEXT,
	"BODY"	TEXT,
	"ISSUE_ID"	INTEGER NOT NULL,
	"CLOSED_BY"	TEXT,
	"TIME_TAKEN"	NUMERIC,
	"PROCESSED_TITLES"	TEXT COLLATE BINARY,
	"PROCESSED_BODY"	TEXT,
	PRIMARY KEY("ISSUE_ID")
);
CREATE TABLE "LABEL" (
	"ISSUE_ID"	INTEGER,
	"NAME"	TEXT,
	"COLOR"	TEXT,
	FOREIGN KEY("ISSUE_ID") REFERENCES "ISSUE"("ISSUE_ID")
);
CREATE TABLE "PACKAGES" (
	"ISSUE_ID"	INTEGER,
	"ID"	INTEGER,
	"NAME"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE PULL_RQ (
    PR_ID INT PRIMARY KEY,
    ISSUE_ID INT,
    REPO_ID INT,
    USER_ID INT,
    TITLE VARCHAR(255),
    BODY TEXT,
    STATE VARCHAR(50),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME,
    CLOSED_AT DATETIME,
    MERGED_AT DATETIME,
    MERGE_COMMIT_SHA VARCHAR(40),
    HEAD_REF VARCHAR(255),
    BASE_REF VARCHAR(255),
    MERGEABLE BOOLEAN,
    MERGED BOOLEAN,
    COMMENTS_COUNT INT,
    REVIEW_COMMENTS_COUNT INT,
    COMMITS_COUNT INT,
    ADDITIONS INT,
    DELETIONS INT,
    CHANGED_FILES_COUNT INT
);

CREATE TABLE pr_review_comments (
    COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PR_NO INT,
    ISSUE_ID INT,
    USER_ID INT,
    COMMENT TEXT,
    CREATED_AT DATETIME
);

CREATE TABLE pr_reviewers (
    REVIEWER_ID INT AUTO_INCREMENT,
    PR_NO INT,
    ISSUE_ID INT,
    USER_ID VARCHAR(255),  -- Adjust size as needed
    PRIMARY KEY (REVIEWER_ID)

);

CREATE TABLE pr_files_changed (
    FILE_ID INT AUTO_INCREMENT PRIMARY KEY,
    PR_NO INT,
    ISSUE_ID INT,
    FILE_NAME VARCHAR(255),
    STATUS VARCHAR(100)
);

CREATE TABLE TEAMS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TEAM_NAME VARCHAR(255),
    PR_NO INT,
    ISSUE_ID INT
);